version: '3.8'

services:
  web:
    build: ./src
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 4000
    volumes:
      - ./src:/usr/src/app
    ports:
      - 4000:4000
    environment:
      - ENVIRONMENT=development
      - 'DATABASE_URL=sqlite://:memory:'
      - TOKEN_SECRET=do_not_show_this_to_anyone
