version: "3.8"

services:
  web:
    build: ./src
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0
    volumes:
      - ./src:/usr/src/app
    ports:
      - 8000:8000
    environment:
      - ENVIRONMENT=development
      - "DATABASE_URL=sqlite://:memory:"
      - TOKEN_SECRET=do_not_show_this_to_anyone
